import 'dart:convert'; import 'dart:io';
import 'package:audio_service/audio_service.dart'; import 'package:flutter_cache_manager/flutter_cache_manager.dart'; import 'package:http/http.dart' as http; import 'package:just_audio/just_audio.dart';
import 'quran_service.dart'; import 'reciter_service.dart';
class AudioQuranException implements Exception { final String message; const AudioQuranException(this.message); @override String toString()=>message; }
class AudioQuranService { final AudioPlayer player=AudioPlayer(); static const quranAudioCdn='https://verses.quran.foundation'; static const quranComApiBase='https://api.quran.com/api/v4'; static const requestTimeout=Duration(seconds:12); static const maxRetries=3; static const playlistBatchSize=12;
  Future<String> getAyahAudioUrl({required int surahNumber, required int ayahNumber, int? recitationId}) async { final rid=recitationId ?? await ReciterService.getSelectedReciterId(); final uri=Uri.parse('$quranComApiBase/recitations/$rid/by_ayah/$surahNumber:$ayahNumber?fields=url'); Exception? last; for(int a=1;a<=maxRetries;a++){ try{ final r=await http.get(uri,headers:{'Accept':'application/json'}).timeout(requestTimeout); if(r.statusCode!=200) throw AudioQuranException('فشل طلب الصوت من Quran.com، كود الخطأ: ${r.statusCode}'); final body=json.decode(r.body) as Map<String,dynamic>; final files=body['audio_files']; if(files is! List || files.isEmpty) throw const AudioQuranException('لا يوجد ملف صوت لهذه الآية.'); final url=(files.first as Map<String,dynamic>)['url'] as String?; if(url==null||url.isEmpty) throw const AudioQuranException('رابط الصوت فارغ.'); if(url.startsWith('http')) return url; return '$quranAudioCdn${url.startsWith('/')?url:'/$url'}'; } on SocketException catch(e){ last=e; } on PlayerException catch(e){ last=e; } catch(e){ last=Exception(e.toString()); } await Future.delayed(Duration(milliseconds:350*a)); } throw AudioQuranException('تعذر تحميل الصوت بعد $maxRetries محاولات. ${last ?? ''}'); }
  Future<File> getCachedAudioFile({required int surahNumber, required int ayahNumber, int? recitationId}) async { final url=await getAyahAudioUrl(surahNumber:surahNumber,ayahNumber:ayahNumber,recitationId:recitationId); return DefaultCacheManager().getSingleFile(url); }
  Future<void> playAyah({required int surahNumber, required int ayahNumber, int? recitationId, bool useCache=true, String? surahName}) async { final rid=recitationId ?? await ReciterService.getSelectedReciterId(); final reciter=ReciterService.getReciterById(rid); final tag=MediaItem(id:'$surahNumber:$ayahNumber', title:'سورة ${surahName ?? surahNumber} - آية $ayahNumber', artist:reciter.name, album:'وردي | Wirdi'); if(useCache){ final file=await getCachedAudioFile(surahNumber:surahNumber, ayahNumber:ayahNumber, recitationId:rid); await player.setAudioSource(AudioSource.file(file.path, tag: tag)); } else { final url=await getAyahAudioUrl(surahNumber:surahNumber, ayahNumber:ayahNumber, recitationId:rid); await player.setAudioSource(AudioSource.uri(Uri.parse(url), tag: tag)); } await player.play(); }
  Future<void> playSurah({required Surah surah, int startAyah=1, int? recitationId}) async { final rid=recitationId ?? await ReciterService.getSelectedReciterId(); final reciter=ReciterService.getReciterById(rid); final ayahs=surah.ayahs.where((a)=>a.number>=startAyah).toList(); final sources=<AudioSource>[]; for(int i=0;i<ayahs.length;i+=playlistBatchSize){ final batch=ayahs.skip(i).take(playlistBatchSize).toList(); final urls=await Future.wait(batch.map((a)=>getAyahAudioUrl(surahNumber:surah.number, ayahNumber:a.number, recitationId:rid))); for(int j=0;j<batch.length;j++){ final a=batch[j]; sources.add(AudioSource.uri(Uri.parse(urls[j]), tag: MediaItem(id:'${surah.number}:${a.number}', title:'سورة ${surah.name} - آية ${a.number}', artist:reciter.name, album:'وردي | Wirdi'))); } } await player.setAudioSources(sources); await player.play(); }
  Future<void> playAyahRange({required int surahNumber, required int startAyah, required int endAyah, int? recitationId}) async { final surah=await QuranService.loadSurah(surahNumber); final partial=Surah(number:surah.number,name:surah.name,englishName:surah.englishName,ayahs:surah.ayahs.where((a)=>a.number>=startAyah&&a.number<=endAyah).toList()); await playSurah(surah: partial, startAyah: startAyah, recitationId: recitationId); }
  Future<void> next()=>player.seekToNext(); Future<void> previous()=>player.seekToPrevious(); Future<void> pause()=>player.pause(); Future<void> stop()=>player.stop(); Future<void> dispose()=>player.dispose(); }
