import 'package:adhan/adhan.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:geolocator/geolocator.dart';
import 'package:timezone/data/latest_all.dart' as tz;
import 'package:timezone/timezone.dart' as tz;
class NotificationService { static final FlutterLocalNotificationsPlugin notificationsPlugin = FlutterLocalNotificationsPlugin();
  static Future<void> initialize() async { const android=AndroidInitializationSettings('@mipmap/ic_launcher'); const ios=DarwinInitializationSettings(requestAlertPermission:true,requestBadgePermission:true,requestSoundPermission:true); tz.initializeTimeZones(); await notificationsPlugin.initialize(const InitializationSettings(android:android,iOS:ios)); await requestNotificationPermission(); }
  static Future<void> requestNotificationPermission() async { await notificationsPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()?.requestNotificationsPermission(); await notificationsPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()?.requestExactAlarmsPermission(); await notificationsPlugin.resolvePlatformSpecificImplementation<IOSFlutterLocalNotificationsPlugin>()?.requestPermissions(alert:true,badge:true,sound:true); }
  static Future<Position?> getUserLocation() async { if(!await Geolocator.isLocationServiceEnabled()) return null; var p=await Geolocator.checkPermission(); if(p==LocationPermission.denied) p=await Geolocator.requestPermission(); if(p==LocationPermission.denied||p==LocationPermission.deniedForever) return null; return Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high); }
  static Future<void> scheduleAzkarNotificationsByPrayerTimes() async { final pos=await getUserLocation(); if(pos==null){ await scheduleFallbackNotifications(); return; } final coords=Coordinates(pos.latitude,pos.longitude); final params=CalculationMethod.egyptian.getParameters()..madhab=Madhab.shafi; final now=DateTime.now(); final times=PrayerTimes.today(coords,params); DateTime fajr=times.fajr, maghrib=times.maghrib; if(fajr.isBefore(now)){ final t=now.add(const Duration(days:1)); fajr=PrayerTimes(coords,DateComponents(t.year,t.month,t.day),params).fajr; } if(maghrib.isBefore(now)){ final t=now.add(const Duration(days:1)); maghrib=PrayerTimes(coords,DateComponents(t.year,t.month,t.day),params).maghrib; } await notificationsPlugin.cancel(1); await notificationsPlugin.cancel(2); await notificationsPlugin.cancel(3); await scheduleNotification(id:1,title:'أذكار الصباح',body:'حان وقت أذكار الصباح 🌿',scheduledDate:fajr); await scheduleNotification(id:2,title:'أذكار المساء',body:'حان وقت أذكار المساء 🌙',scheduledDate:maghrib); final sleep=DateTime(now.year,now.month,now.day,22).isBefore(now)?DateTime(now.year,now.month,now.day,22).add(const Duration(days:1)):DateTime(now.year,now.month,now.day,22); await scheduleNotification(id:3,title:'أذكار النوم',body:'لا تنس أذكار النوم ⭐',scheduledDate:sleep,repeatsDaily:true); }
  static Future<void> scheduleNotification({required int id, required String title, required String body, required DateTime scheduledDate, bool repeatsDaily=false}) async { await notificationsPlugin.zonedSchedule(id,title,body,tz.TZDateTime.from(scheduledDate,tz.local), const NotificationDetails(android:AndroidNotificationDetails('wirdi_daily_channel','Wirdi Daily Notifications',channelDescription:'Daily azkar and prayer notifications',importance:Importance.high,priority:Priority.high), iOS:DarwinNotificationDetails(presentAlert:true,presentBadge:true,presentSound:true)), androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle, uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime, matchDateTimeComponents: repeatsDaily?DateTimeComponents.time:null); }
  static Future<void> scheduleFallbackNotifications() async { final now=DateTime.now(); DateTime morning=DateTime(now.year,now.month,now.day,7), evening=DateTime(now.year,now.month,now.day,18), sleep=DateTime(now.year,now.month,now.day,22); if(morning.isBefore(now)) morning=morning.add(const Duration(days:1)); if(evening.isBefore(now)) evening=evening.add(const Duration(days:1)); if(sleep.isBefore(now)) sleep=sleep.add(const Duration(days:1)); await notificationsPlugin.cancel(1); await notificationsPlugin.cancel(2); await notificationsPlugin.cancel(3); await scheduleNotification(id:1,title:'أذكار الصباح',body:'لا تنس أذكار الصباح 🌿',scheduledDate:morning,repeatsDaily:true); await scheduleNotification(id:2,title:'أذكار المساء',body:'لا تنس أذكار المساء 🌙',scheduledDate:evening,repeatsDaily:true); await scheduleNotification(id:3,title:'أذكار النوم',body:'لا تنس أذكار النوم ⭐',scheduledDate:sleep,repeatsDaily:true); }
}
