import 'dart:convert';
import 'package:flutter/services.dart';
class QuranService {
  static List<SurahIndex>? _cachedIndex; static List<QuranSearchResult>? _cachedSearchIndex; static final Map<int, Surah> _cachedSurahs = {}; static final Map<int, Map<int, String>> _cachedTafsir = {};
  static Future<List<SurahIndex>> loadQuranIndex() async { if (_cachedIndex != null) return _cachedIndex!; final s = await rootBundle.loadString('assets/quran_index.json'); final data = json.decode(s) as List; _cachedIndex = data.map((e)=>SurahIndex.fromJson(e)).toList(); return _cachedIndex!; }
  static Future<Surah> loadSurah(int n) async { if (_cachedSurahs.containsKey(n)) return _cachedSurahs[n]!; final s = await rootBundle.loadString('assets/quran/$n.json'); final surah = Surah.fromJson(json.decode(s)); _cachedSurahs[n] = surah; return surah; }
  static Future<Map<int,String>> loadTafsirForSurah(int n) async { if (_cachedTafsir.containsKey(n)) return _cachedTafsir[n]!; try { final s = await rootBundle.loadString('assets/tafsir/$n.json'); final data = json.decode(s) as List; final out = <int,String>{}; for (final item in data) { out[item['ayah']] = item['text'] ?? ''; } _cachedTafsir[n]=out; return out; } catch (_) { _cachedTafsir[n] = {}; return {}; } }
  static Future<List<QuranSearchResult>> loadSearchIndex() async { if (_cachedSearchIndex != null) return _cachedSearchIndex!; final s = await rootBundle.loadString('assets/quran_search_index.json'); final data = json.decode(s) as List; _cachedSearchIndex = data.map((e)=>QuranSearchResult.fromJson(e)).toList(); return _cachedSearchIndex!; }
  static String normalizeArabic(String input) => input.replaceAll(RegExp(r'[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]'), '').replaceAll('أ','ا').replaceAll('إ','ا').replaceAll('آ','ا').replaceAll('ى','ي').replaceAll('ة','ه').replaceAll('ؤ','و').replaceAll('ئ','ي').replaceAll(RegExp(r'\s+'),' ').trim();
  static Future<List<QuranSearchResult>> searchQuran(String query) async { final q = normalizeArabic(query.trim()); if (q.isEmpty) return []; final idx = await loadSearchIndex(); return idx.where((i){ final t=normalizeArabic(i.text); final s=normalizeArabic(i.surahName); return t.contains(q)||s.contains(q)||i.surahNumber.toString()==q||i.ayahNumber.toString()==q; }).toList(); }
}
class SurahIndex { final int number; final String name; final String englishName; final int ayahCount; SurahIndex({required this.number, required this.name, required this.englishName, required this.ayahCount}); factory SurahIndex.fromJson(Map<String,dynamic> j)=>SurahIndex(number:j['number'], name:j['name'], englishName:j['englishName']??'', ayahCount:j['ayahCount']??0); }
class Surah { final int number; final String name; final String englishName; final List<Ayah> ayahs; Surah({required this.number, required this.name, required this.englishName, required this.ayahs}); factory Surah.fromJson(Map<String,dynamic> j)=>Surah(number:j['number'], name:j['name'], englishName:j['englishName']??'', ayahs:(j['ayahs'] as List).map((e)=>Ayah.fromJson(e)).toList()); }
class Ayah { final int number; final String text; Ayah({required this.number, required this.text}); factory Ayah.fromJson(Map<String,dynamic> j)=>Ayah(number:j['number'], text:j['text']); }
class QuranSearchResult { final int surahNumber; final String surahName; final int ayahNumber; final String text; QuranSearchResult({required this.surahNumber, required this.surahName, required this.ayahNumber, required this.text}); factory QuranSearchResult.fromJson(Map<String,dynamic> j)=>QuranSearchResult(surahNumber:j['surahNumber'], surahName:j['surahName'], ayahNumber:j['ayahNumber'], text:j['text']); }
